package com.suw1labs.worktracker.data

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.sqlite.SQLiteConnection
import com.suw1labs.worktracker.data.dao.AttendanceDao
import com.suw1labs.worktracker.data.dao.BackupDao
import com.suw1labs.worktracker.data.dao.DayRecordDao
import com.suw1labs.worktracker.data.dao.SettingsDao
import com.suw1labs.worktracker.data.dao.ProjectDao
import com.suw1labs.worktracker.data.dao.TimeEntryDao
import com.suw1labs.worktracker.data.dao.WorkTaskDao
import com.suw1labs.worktracker.data.model.AppSettings
import com.suw1labs.worktracker.data.model.AttendanceSession
import com.suw1labs.worktracker.data.model.DayRecord
import com.suw1labs.worktracker.data.model.Project
import com.suw1labs.worktracker.data.model.TimeEntry
import com.suw1labs.worktracker.data.model.WorkTask
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.IO
import kotlin.concurrent.Volatile

const val DATABASE_NAME = "work_tracker.db"

/**
 * Current schema version.
 *
 * Bumping it requires, in the same change:
 * 1. a `Migration` from the previous version added to [ALL_MIGRATIONS] (see `Migrations.kt`),
 * 2. the new `composeApp/schemas/…/<version>.json` generated by the build (`exportSchema = true`) and committed,
 * 3. `MigrationTest` (desktop tests) passing – it replays every migration and validates the result.
 *
 * Backups record the schema version they were written with, so older backups can still be
 * imported after the schema moves on (missing fields take their defaults).
 */
const val DATABASE_VERSION = 10

@Database(
    entities = [Project::class, WorkTask::class, TimeEntry::class, AttendanceSession::class, DayRecord::class, AppSettings::class],
    version = DATABASE_VERSION,
    exportSchema = true
)
@ConstructedBy(AppDatabaseConstructor::class)
abstract class AppDatabase : RoomDatabase() {
    abstract fun projectDao(): ProjectDao
    abstract fun workTaskDao(): WorkTaskDao
    abstract fun timeEntryDao(): TimeEntryDao
    abstract fun attendanceDao(): AttendanceDao
    abstract fun dayRecordDao(): DayRecordDao
    abstract fun settingsDao(): SettingsDao
    abstract fun backupDao(): BackupDao

    /**
     * Creates the default settings row and the built-in "Unproductive" project with its tasks
     * (meeting, coffee break, …) when they do not exist yet. Real projects are entered from the
     * list provided by project management.
     */
    suspend fun seedDefaults() {
        if (settingsDao().getSettings() == null) settingsDao().upsert(AppSettings())
        val projects = projectDao()
        if (projects.findByCode(Project.UNPRODUCTIVE_CODE) == null) {
            val id = projects.insertProject(
                Project(
                    code = Project.UNPRODUCTIVE_CODE,
                    name = "Unproductive",
                    client = "",
                    colorHex = "#F59E0B",
                    isProductive = false
                )
            )
            DEFAULT_UNPRODUCTIVE_TASKS.forEach { title ->
                workTaskDao().insertTask(WorkTask(projectId = id, title = title, priority = "LOW", reminderEnabled = false))
            }
        }
    }

    companion object {
        val DEFAULT_UNPRODUCTIVE_TASKS: List<String> = listOf(
            "Meeting", "Coffee / Smoke break", "Informal meeting", "Uncategorized"
        )
    }
}

// The Room compiler generates the `actual` implementations for every target.
@Suppress("KotlinNoActualForExpect")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}

/**
 * Records whether the database file was created from scratch, so the caller can
 * seed demo data exactly once (mirrors the old Android `RoomDatabase.Callback.onCreate`).
 */
class DatabaseCreationTracker : RoomDatabase.Callback() {
    @Volatile
    var wasCreated: Boolean = false
        private set

    override fun onCreate(connection: SQLiteConnection) {
        super.onCreate(connection)
        wasCreated = true
    }
}

/**
 * Finishes configuring a platform-provided builder (which already has its SQLite driver set)
 * with the options shared by all platforms.
 */
fun RoomDatabase.Builder<AppDatabase>.buildAppDatabase(
    creationTracker: DatabaseCreationTracker,
    queryDispatcher: CoroutineDispatcher = Dispatchers.IO
): AppDatabase = addCallback(creationTracker)
    .addMigrations(*ALL_MIGRATIONS)
    // Versions 1–5 held the old billing-oriented model with demo data only; they are recreated from
    // scratch. From version 6 on, real data lives in the file: a missing migration makes Room refuse
    // to open the database instead of silently wiping it, and MigrationTest catches that before release.
    .fallbackToDestructiveMigrationFrom(dropAllTables = true, 1, 2, 3, 4, 5)
    // Write-ahead logging on every platform: readers (UI flows, widgets) never block the writer.
    .setJournalMode(RoomDatabase.JournalMode.WRITE_AHEAD_LOGGING)
    .setQueryCoroutineContext(queryDispatcher)
    .build()
